// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkbdqekqrycrgxpghnpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rYmRxZWtxcnljcmd4cGdobnB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNTk3MTgsImV4cCI6MjA3MzYzNTcxOH0._7K-G0o3H9XMg-8QUlFyFTjbcy-TDa15u-5_S2d7nIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});